set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
create_clock -period 8.000 -name eth_rxc [get_ports net_rxc]
set_property -dict {PACKAGE_PIN AG10 IOSTANDARD LVDS} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN T26 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports net_rst_n]
set_property -dict {PACKAGE_PIN U27 IOSTANDARD LVCMOS33} [get_ports net_rxc]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports net_rx_ctl]
set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS33} [get_ports {net_rxd[0]}]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS33} [get_ports {net_rxd[1]}]
set_property -dict {PACKAGE_PIN V30 IOSTANDARD LVCMOS33} [get_ports {net_rxd[2]}]
set_property -dict {PACKAGE_PIN V25 IOSTANDARD LVCMOS33} [get_ports {net_rxd[3]}]
set_property -dict {PACKAGE_PIN U28 IOSTANDARD LVCMOS33} [get_ports net_txc]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports net_tx_ctl]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports {net_txd[0]}]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports {net_txd[1]}]
set_property -dict {PACKAGE_PIN U29 IOSTANDARD LVCMOS33} [get_ports {net_txd[2]}]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS33} [get_ports {net_txd[3]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports eth1_mdc]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports eth1_mdio]
