#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT_DIR/scripts/component_lib.sh"

ensure_venv client/client-listener/requirements.txt

HOST="${DSQL_HOST:-4btv7qq43k4ztw3tjubmbyf3su.dsql.us-east-2.on.aws}"
REGION="${AWS_REGION:-us-east-2}"
CLIENT_LISTENER_HOST="${CLIENT_LISTENER_HOST:-0.0.0.0}"
CLIENT_LISTENER_PORT="${CLIENT_LISTENER_PORT:-9001}"
CLIENT_LISTENER_AUTH_MODE="${CLIENT_LISTENER_AUTH_MODE:-static-token}"
CLIENT_LISTENER_AUTH_TOKEN="${CLIENT_LISTENER_AUTH_TOKEN:-dev-shared-token}"
CLIENT_LISTENER_ACCOUNT_SESSION_TTL_SECONDS="${CLIENT_LISTENER_ACCOUNT_SESSION_TTL_SECONDS:-43200}"
CLIENT_LISTENER_WORKERS="${CLIENT_LISTENER_WORKERS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)}"
CLIENT_LISTENER_DB_MIN_POOL="${CLIENT_LISTENER_DB_MIN_POOL:-8}"
CLIENT_LISTENER_DB_MAX_POOL="${CLIENT_LISTENER_DB_MAX_POOL:-64}"
CLIENT_LISTENER_METRICS_HOST="${CLIENT_LISTENER_METRICS_HOST:-0.0.0.0}"
CLIENT_LISTENER_METRICS_PORT="${CLIENT_LISTENER_METRICS_PORT:-9101}"

refresh_dsql_dsn CLIENT_LISTENER_DB_DSN "$HOST" "$REGION"

exec env \
  CLIENT_LISTENER_HOST="$CLIENT_LISTENER_HOST" \
  CLIENT_LISTENER_PORT="$CLIENT_LISTENER_PORT" \
  CLIENT_LISTENER_DB_DSN="$CLIENT_LISTENER_DB_DSN" \
  CLIENT_LISTENER_AUTH_MODE="$CLIENT_LISTENER_AUTH_MODE" \
  CLIENT_LISTENER_AUTH_TOKEN="$CLIENT_LISTENER_AUTH_TOKEN" \
  CLIENT_LISTENER_ACCOUNT_SESSION_TTL_SECONDS="$CLIENT_LISTENER_ACCOUNT_SESSION_TTL_SECONDS" \
  CLIENT_LISTENER_WORKERS="$CLIENT_LISTENER_WORKERS" \
  CLIENT_LISTENER_DB_MIN_POOL="$CLIENT_LISTENER_DB_MIN_POOL" \
  CLIENT_LISTENER_DB_MAX_POOL="$CLIENT_LISTENER_DB_MAX_POOL" \
  CLIENT_LISTENER_METRICS_HOST="$CLIENT_LISTENER_METRICS_HOST" \
  CLIENT_LISTENER_METRICS_PORT="$CLIENT_LISTENER_METRICS_PORT" \
  "$PYTHON_BIN" "$SCRIPT_DIR/server.py"
