#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$ROOT_DIR/scripts/component_lib.sh"

ensure_venv matchmaker/requirements.txt

HOST="${MATCHMAKER_DSQL_HOST:-${DSQL_HOST:-4btv7qq43k4ztw3tjubmbyf3su.dsql.us-east-2.on.aws}}"
REGION="${MATCHMAKER_AWS_REGION:-${AWS_REGION:-us-east-2}}"
MATCHMAKER_INSTANCE_ID="${MATCHMAKER_INSTANCE_ID:-matchmaker-a}"
MATCHMAKER_POLL_INTERVAL_MS="${MATCHMAKER_POLL_INTERVAL_MS:-500}"
MATCHMAKER_MARKET_SCAN_LIMIT="${MATCHMAKER_MARKET_SCAN_LIMIT:-50}"
MATCHMAKER_ORDER_SCAN_LIMIT="${MATCHMAKER_ORDER_SCAN_LIMIT:-2000}"
MATCHMAKER_LEASE_SECONDS="${MATCHMAKER_LEASE_SECONDS:-5}"
MATCHMAKER_INSTANCE_INDEX="${MATCHMAKER_INSTANCE_INDEX:-0}"
MATCHMAKER_TOTAL_INSTANCES="${MATCHMAKER_TOTAL_INSTANCES:-1}"
MATCHMAKER_REQUEUE_INTERVAL_MS="${MATCHMAKER_REQUEUE_INTERVAL_MS:-5000}"
MATCHMAKER_METRICS_HOST="${MATCHMAKER_METRICS_HOST:-0.0.0.0}"
MATCHMAKER_METRICS_PORT="${MATCHMAKER_METRICS_PORT:-9111}"

refresh_dsql_dsn MATCHMAKER_DB_DSN "$HOST" "$REGION"

exec env \
  MATCHMAKER_DB_DSN="$MATCHMAKER_DB_DSN" \
  MATCHMAKER_INSTANCE_ID="$MATCHMAKER_INSTANCE_ID" \
  MATCHMAKER_POLL_INTERVAL_MS="$MATCHMAKER_POLL_INTERVAL_MS" \
  MATCHMAKER_MARKET_SCAN_LIMIT="$MATCHMAKER_MARKET_SCAN_LIMIT" \
  MATCHMAKER_ORDER_SCAN_LIMIT="$MATCHMAKER_ORDER_SCAN_LIMIT" \
  MATCHMAKER_LEASE_SECONDS="$MATCHMAKER_LEASE_SECONDS" \
  MATCHMAKER_INSTANCE_INDEX="$MATCHMAKER_INSTANCE_INDEX" \
  MATCHMAKER_TOTAL_INSTANCES="$MATCHMAKER_TOTAL_INSTANCES" \
  MATCHMAKER_REQUEUE_INTERVAL_MS="$MATCHMAKER_REQUEUE_INTERVAL_MS" \
  MATCHMAKER_METRICS_HOST="$MATCHMAKER_METRICS_HOST" \
  MATCHMAKER_METRICS_PORT="$MATCHMAKER_METRICS_PORT" \
  "$PYTHON_BIN" "$SCRIPT_DIR/matchmaker.py"
