# Toolchain
CXX      := clang++
CC       := clang

# Directories
SRC_DIR  := src
INC_DIR  := include
LIB_DIR  := lib
BIN_DIR  := bin
TEST_DIR := test
OBJ_DIR  := build/obj
DEP_DIR  := build/dep

# Main binary
TARGET   := $(BIN_DIR)/hft-tcpstack

# Sources & objects (all *.cpp under src/)
SRCS     := $(shell find $(SRC_DIR) -name "*.cpp")
OBJS     := $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SRCS))

# Test sources — each file has its own main(), so each becomes its own binary.
TEST_SRCS := $(shell find $(TEST_DIR) -name "test_*.cpp")
TEST_OBJS := $(patsubst $(TEST_DIR)/%.cpp, $(OBJ_DIR)/test/%.o, $(TEST_SRCS))
TEST_BINS := $(patsubst $(TEST_DIR)/%.cpp, $(BIN_DIR)/%, $(TEST_SRCS))

# Dependency files (auto-generated by -MMD)
DEPS      := $(patsubst $(OBJ_DIR)/%.o, $(DEP_DIR)/%.d, $(OBJS))
TEST_DEPS := $(patsubst $(OBJ_DIR)/test/%.o, $(DEP_DIR)/test/%.d, $(TEST_OBJS))

# Flags
CXXFLAGS := -std=c++17 \
            -Wall -Wextra -Wpedantic \
            -I$(INC_DIR)

LDFLAGS  :=
LIBS     :=

# Debug / Release modes: make DEBUG=1 or make RELEASE=1
ifdef DEBUG
  CXXFLAGS += -O0 -g3 -fsanitize=address,undefined -DDEBUG
  LDFLAGS  += -fsanitize=address,undefined
else ifdef RELEASE
  CXXFLAGS += -O3 -march=native -flto -DNDEBUG
  LDFLAGS  += -flto
else
  CXXFLAGS += -O2 -g
endif

# Rules
.PHONY: all clean test capture dirs

all: dirs $(TARGET)

# Link main binary
$(TARGET): $(OBJS)
	@echo "  LINK  $@"
	@$(CXX) $(LDFLAGS) $^ -o $@ $(LIBS)

# Compile src/**/*.cpp → build/obj/**/*.o
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@) $(dir $(DEP_DIR)/$*.d)
	@echo "  CXX   $<"
	@$(CXX) $(CXXFLAGS) -MT $@ -MMD -MP -MF $(DEP_DIR)/$*.d -c $< -o $@

# Compile test/test_*.cpp → build/obj/test/test_*.o
$(OBJ_DIR)/test/%.o: $(TEST_DIR)/%.cpp
	@mkdir -p $(dir $@) $(dir $(DEP_DIR)/test/$*.d)
	@echo "  CXX   $<"
	@$(CXX) $(CXXFLAGS) -MT $@ -MMD -MP -MF $(DEP_DIR)/test/$*.d -c $< -o $@

# Link each test object + all src objects (except main.o) into its own binary.
$(BIN_DIR)/test_%: $(OBJ_DIR)/test/test_%.o $(SRC_OBJS_NO_MAIN)
	@mkdir -p $(BIN_DIR)
	@echo "  LINK  $@"
	@$(CXX) $(LDFLAGS) $^ -o $@ $(LIBS)

# Run all test binaries.
test: dirs all $(TEST_BINS)
	@echo ""
	@total_pass=0; total_fail=0; \
	for t in $(TEST_BINS); do \
		echo "--- $$t ---"; \
		./$$t; \
		rc=$$?; \
		if [ $$rc -ne 0 ]; then total_fail=$$((total_fail+1)); \
		else total_pass=$$((total_pass+1)); fi; \
		echo ""; \
	done; \
	echo "=== $$total_pass suite(s) passed, $$total_fail suite(s) failed ==="

# Per-phase convenience targets.
test-phase1: dirs all $(BIN_DIR)/test_raw_socket
	@./$(BIN_DIR)/test_raw_socket

test-phase2: dirs all $(BIN_DIR)/test_checksum
	@./$(BIN_DIR)/test_checksum

test-phase3: dirs all $(BIN_DIR)/test_retransmit $(BIN_DIR)/test_tcp_state
	@echo "--- test_retransmit ---"
	@./$(BIN_DIR)/test_retransmit
	@echo ""
	@echo "--- test_tcp_state ---"
	@./$(BIN_DIR)/test_tcp_state

# Phase 2 wire validation: build main binary then run tcpdump capture script
capture: dirs $(TARGET)
	@sudo ./scripts/capture_syn.sh

# Create required directories
dirs:
	@mkdir -p $(BIN_DIR) $(OBJ_DIR) $(DEP_DIR)

clean:
	rm -rf build/ $(BIN_DIR)/

# Pull in generated dependency files so headers trigger recompilation
-include $(DEPS) $(TEST_DEPS)
