# -*- coding: utf-8 -*-
"""HFT-Semester-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyFwCdAdmuY-uO09oTnaNeMt73UsIxww
"""

!pip install gymnasium stable-baselines3 pandas numpy -q

import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

# Load and filter to one symbol
SYMBOL = 4
book_df = pd.read_csv('/content/drive/MyDrive/HFT-SP25-Semester-Project/rl_book_data.csv')
trade_df = pd.read_csv('/content/drive/MyDrive/HFT-SP25-Semester-Project/rl_trade_data.csv')

print(book_df.head(1))
print(trade_df.head(1))

book = book_df[book_df['symbol'] == SYMBOL].reset_index(drop=True)
trades = trade_df[trade_df['symbol'] == SYMBOL].reset_index(drop=True)

# Drop rows where book is one-sided
book = book[(book['mid_price'] > 0) & (book['ask_price_1'] > 0) & (book['spread'] >= 0)].reset_index(drop=True)
print(f"Book rows: {len(book)}, Trade rows: {len(trades)}")

print(book_df['spread'].describe())
print(book_df['spread'].value_counts().head(10))

book_clean = book_df[
    (book_df['mid_price'] > 0) &
    (book_df['ask_price_1'] > 0) &
    (book_df['spread'] > 0) &
    (book_df['ask_price_1'] > book_df['bid_price_1'])
].reset_index(drop=True)
print(f"Rows after filtering: {len(book_clean)}")

print(book_df[book_df['spread'] >= 0].groupby('symbol').size().sort_values(ascending=False))

import gymnasium as gym
from gymnasium import spaces

class OrderExecutionEnv(gym.Env):

    # Action meanings:
    # 0: do nothing
    # 1: passive small  — 10% of remaining, post at bid (low fill prob)
    # 2: passive large  — 20% of remaining, post at ask (moderate fill)
    # 3: aggressive     — 30% of remaining, take ask
    # 4: market order   — 50% of remaining, take ask immediately

    FILL_PROBS  = [0.0, 0.25, 0.60, 1.0, 1.0]   # probability of fill per action
    ORDER_FRACS = [0.0, 0.10, 0.20, 0.30, 0.50]  # fraction of remaining inventory

    def __init__(self, book_df, parent_order_size=100,
                 episode_length=50, tick_size=0.05,
                 inventory_penalty=2.0):
        super().__init__()
        self.book         = book_df.reset_index(drop=True)
        self.order_size   = parent_order_size
        self.ep_len       = episode_length
        self.tick         = tick_size
        self.inv_penalty  = inventory_penalty

        self.action_space = spaces.Discrete(5)

        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(7,), dtype=np.float32
        )

    def reset(self, seed=None):
        super().reset(seed=seed)
        max_start = len(self.book) - self.ep_len - 1
        self.idx          = np.random.randint(0, max_start)
        self.step_num     = 0
        self.remaining    = self.order_size
        self.total_cost   = 0.0
        self.total_filled = 0
        self.decision_price = self.book.at[self.idx, 'mid_price']
        return self._obs(), {}

    def _obs(self):
        r = self.book.iloc[self.idx]
        #State space
        return np.array([
            self.remaining / self.order_size,                        # inventory urgency
            1.0 - self.step_num / self.ep_len,                       # time urgency
            r['spread'],                                             # bid-ask spread
            r['imbalance_l1'],                                       # L1 book imbalance
            r['imbalance_l3'],                                       # L3 book imbalance
            r['ask_qty_1'] / self.order_size,                        # ask liquidity
            r['bid_qty_1'] / self.order_size,                        # bid liquidity
        ], dtype=np.float32)

    def _simulate_fill(self, action, row):
        if self.remaining <= 0 or action == 0:
            return 0, 0.0

        ask_p = row['ask_price_1']
        ask_q = row['ask_qty_1']
        if ask_p <= 0 or ask_q <= 0:
            return 0, 0.0

        # Determine order size
        qty = max(1, int(self.ORDER_FRACS[action] * self.remaining))
        qty = min(qty, self.remaining)

        # For passive orders, fill probabilistically and cap at available qty
        if action in (1, 2):
            if np.random.random() > self.FILL_PROBS[action]:
                return 0, 0.0
            fill_qty  = min(qty, int(ask_q))
            # Never fill below mid
            fill_price = max(ask_p - self.tick, row['mid_price']) if action == 1 else ask_p
            return fill_qty, fill_price

        # For aggressive/market orders, always fill, walk book if needed
        fill_qty  = min(qty, int(ask_q))
        fill_price = ask_p
        return fill_qty, fill_price

    def step(self, action):
        row = self.book.iloc[self.idx]
        fill_qty, fill_price = self._simulate_fill(action, row)

        reward = 0.0
        if fill_qty > 0:
            self.total_cost   += fill_qty * fill_price
            self.total_filled += fill_qty
            self.remaining    -= fill_qty
            # Per-step IS penalty (cost above decision price)
            reward -= (fill_price - self.decision_price) * fill_qty

        self.step_num += 1
        self.idx      += 1

        terminated = self.remaining <= 0
        truncated  = self.step_num >= self.ep_len

        # Terminal inventory penalty
        if truncated and self.remaining > 0:
            worst_price = self.book.iloc[self.idx - 1]['ask_price_1'] + self.book.iloc[self.idx - 1]['spread']
            penalty = self.inv_penalty * self.remaining * max(worst_price - self.decision_price, self.tick)
            reward -= penalty

        return self._obs(), reward, terminated, truncated, {}

    def implementation_shortfall(self):
        if self.total_filled == 0:
            return 0.0
        avg_exec = self.total_cost / self.total_filled
        return avg_exec - self.decision_price

env = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)
obs, _ = env.reset()
print("Obs shape:", obs.shape)
print("Sample obs:", obs)

done = False
total_reward = 0
while not done:
    action = env.action_space.sample()
    obs, reward, terminated, truncated, _ = env.step(action)
    total_reward += reward
    done = terminated or truncated

print(f"Total reward: {total_reward:.4f}")
print(f"Implementation shortfall: {env.implementation_shortfall():.4f}")
print(f"Shares filled: {env.total_filled} / {env.order_size}")

def run_twap(env, n_episodes=100):
    results = []
    for _ in range(n_episodes):
        obs, _ = env.reset()
        done = False
        step = 0
        while not done:
            # Equal slices at every step (always action 3 - aggressive, 30%)
            action = 3
            obs, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
        results.append({
            'IS': env.implementation_shortfall(),
            'filled': env.total_filled,
            'pct_filled': env.total_filled / env.order_size
        })
    return pd.DataFrame(results)

def run_vwap(env, trade_df, n_episodes=100):
    results = []
    for _ in range(n_episodes):
        obs, _ = env.reset()
        done = False
        step = 0
        while not done:
            # aggression scales with remaining time urgency
            time_remaining = 1.0 - step / env.ep_len
            if time_remaining > 0.6:
                action = 1  # early: be passive
            elif time_remaining > 0.3:
                action = 2  # mid: moderate
            else:
                action = 3  # late: aggressive to ensure completion
            obs, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
            step += 1
        results.append({
            'IS': env.implementation_shortfall(),
            'filled': env.total_filled,
            'pct_filled': env.total_filled / env.order_size
        })
    return pd.DataFrame(results)

env = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)

twap_results = run_twap(env, n_episodes=200)
vwap_results = run_vwap(env, trade_df=trades, n_episodes=200)

print("=== TWAP ===")
print(f"Mean IS:     {twap_results['IS'].mean():.4f}")
print(f"Std IS:      {twap_results['IS'].std():.4f}")
print(f"Pct Filled:  {twap_results['pct_filled'].mean():.2%}")

print("\n=== VWAP ===")
print(f"Mean IS:     {vwap_results['IS'].mean():.4f}")
print(f"Std IS:      {vwap_results['IS'].std():.4f}")
print(f"Pct Filled:  {vwap_results['pct_filled'].mean():.2%}")

import matplotlib.pyplot as plt
from stable_baselines3.common.callbacks import BaseCallback

class RewardLoggerCallback(BaseCallback):
    def __init__(self, verbose=0):
        super().__init__(verbose)
        self.episode_rewards = []
        self.episode_lengths = []
        self._current_rewards = None

    def _on_training_start(self):
        self._current_rewards = np.zeros(self.training_env.num_envs)

    def _on_step(self):
        for info in self.locals['infos']:
          if 'episode' in info:
            self.episode_rewards.append(info['episode']['r'])
        return True

    def plot(self, window=50):
        rewards = self.episode_rewards
        smoothed = pd.Series(rewards).rolling(window).mean()
        plt.figure(figsize=(12, 4))
        plt.plot(rewards, alpha=0.3, label='Raw')
        plt.plot(smoothed, label=f'Smoothed (window={window})')
        plt.axhline(y=-twap_results['IS'].mean()*100, color='r',
                    linestyle='--', label='TWAP baseline')
        plt.axhline(y=-vwap_results['IS'].mean()*100, color='g',
                    linestyle='--', label='VWAP baseline')
        plt.xlabel('Episode')
        plt.ylabel('Total Reward')
        plt.title('PPO Training Reward Curve')
        plt.legend()
        plt.tight_layout()
        plt.show()

!pip install stable-baselines3 -q

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv
from stable_baselines3.common.callbacks import EvalCallback, CallbackList
from stable_baselines3.common.monitor import Monitor

SAVE_PATH = '/content/drive/MyDrive/HFT-SP25-Semester-Project'

def make_env():
    env = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)
    return Monitor(env)

vec_env  = make_vec_env(make_env, n_envs=8, vec_env_cls=SubprocVecEnv)
eval_env = Monitor(OrderExecutionEnv(book, parent_order_size=100, episode_length=50))

eval_callback = EvalCallback(eval_env,
                             eval_freq=5000,
                             best_model_save_path=f'{SAVE_PATH}/ppo_best',
                             verbose=1)

model = PPO(
    "MlpPolicy", vec_env,
    learning_rate=3e-4,
    n_steps=256,
    batch_size=64,
    n_epochs=10,
    gamma=0.99,
    ent_coef=0.01,
    verbose=1,
    device='cpu',
    tensorboard_log=f'{SAVE_PATH}/ppo_logs'
)

reward_logger = RewardLoggerCallback()
callback = CallbackList([eval_callback, reward_logger])

model.learn(total_timesteps=1_000_000, callback=callback)
model.save(f'{SAVE_PATH}/ppo_final')

print(f"Training complete")
print(f"Episodes captured: {len(reward_logger.episode_rewards)}")

reward_logger.plot()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def plot_reward_curve(reward_logger, window=100):
    rewards = reward_logger.episode_rewards
    smoothed = pd.Series(rewards).rolling(window).mean()
    plt.figure(figsize=(12, 4))
    plt.plot(smoothed, color='steelblue', label=f'Smoothed (window={window})')
    plt.axhline(y=-twap_results['IS'].mean()*100, color='r', linestyle='--', label=f'TWAP IS={twap_results["IS"].mean():.4f}')
    plt.axhline(y=-vwap_results['IS'].mean()*100, color='g', linestyle='--', label=f'VWAP IS={vwap_results["IS"].mean():.4f}')
    plt.xlabel('Episode')
    plt.ylabel('Total Reward')
    plt.title('PPO Training Reward Curve')
    plt.legend()
    plt.tight_layout()
    plt.xlim(0, len(rewards))
    plt.ylim(bottom=min(smoothed.dropna()) * 1.2, top=0.5)
    plt.savefig(f'{SAVE_PATH}/reward_curve.png', dpi=150)
    plt.show()

def evaluate_ppo(model, env, n_episodes=200):
    results = []
    for _ in range(n_episodes):
        obs, _ = env.reset()
        done = False
        while not done:
            action, _ = model.predict(obs, deterministic=True)
            obs, _, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
        results.append({
            'IS': env.implementation_shortfall(),
            'filled': env.total_filled,
            'pct_filled': env.total_filled / env.order_size
        })
    return pd.DataFrame(results)

eval_env_raw = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)
ppo_results  = evaluate_ppo(model, eval_env_raw, n_episodes=200)

def plot_is_distribution():
    plt.figure(figsize=(12, 4))
    bins = np.linspace(-0.05, 0.15, 50)
    plt.hist(twap_results['IS'], bins=bins, alpha=0.5, label='TWAP', color='red')
    plt.hist(vwap_results['IS'], bins=bins, alpha=0.5, label='VWAP', color='green')
    plt.hist(ppo_results['IS'],  bins=bins, alpha=0.5, label='PPO',  color='steelblue')
    plt.axvline(twap_results['IS'].mean(), color='red',      linestyle='--')
    plt.axvline(vwap_results['IS'].mean(), color='green',    linestyle='--')
    plt.axvline(ppo_results['IS'].mean(),  color='steelblue',linestyle='--')
    plt.xlabel('Implementation Shortfall')
    plt.ylabel('Frequency')
    plt.title('IS Distribution: TWAP vs VWAP vs PPO')
    plt.legend()
    plt.tight_layout()
    plt.savefig(f'{SAVE_PATH}/is_distribution.png', dpi=150)
    plt.show()

def print_summary():
    summary = pd.DataFrame({
        'Strategy': ['TWAP', 'VWAP', 'PPO'],
        'Mean IS':  [twap_results['IS'].mean(),  vwap_results['IS'].mean(),  ppo_results['IS'].mean()],
        'Std IS':   [twap_results['IS'].std(),   vwap_results['IS'].std(),   ppo_results['IS'].std()],
        'Pct Filled': [twap_results['pct_filled'].mean(), vwap_results['pct_filled'].mean(), ppo_results['pct_filled'].mean()]
    })
    summary['Mean IS']    = summary['Mean IS'].map('{:.4f}'.format)
    summary['Std IS']     = summary['Std IS'].map('{:.4f}'.format)
    summary['Pct Filled'] = summary['Pct Filled'].map('{:.2%}'.format)
    print(summary.to_string(index=False))

def plot_action_distribution():
    actions = []
    env = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)
    for _ in range(200):
        obs, _ = env.reset()
        done = False
        while not done:
            action, _ = model.predict(obs, deterministic=True)
            actions.append(int(action))
            obs, _, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
    labels = ['Do Nothing', 'Passive Small', 'Passive Large', 'Aggressive', 'Market']
    counts = [actions.count(i) for i in range(5)]
    plt.figure(figsize=(8, 4))
    plt.bar(labels, counts, color='steelblue')
    plt.ylabel('Count')
    plt.title('PPO Action Distribution')
    plt.tight_layout()
    plt.savefig(f'{SAVE_PATH}/action_dist.png', dpi=150)
    plt.show()

# Run all
plot_reward_curve(reward_logger)
plot_is_distribution()
print_summary()
plot_action_distribution()

def plot_action_over_time():
    action_by_step = [[] for _ in range(50)]
    env = OrderExecutionEnv(book, parent_order_size=100, episode_length=50)
    for _ in range(200):
        obs, _ = env.reset()
        done = False
        step = 0
        while not done:
            action, _ = model.predict(obs, deterministic=True)
            action_by_step[step].append(int(action))
            obs, _, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
            step += 1
    avg_actions = [np.mean(a) for a in action_by_step if a]
    plt.figure(figsize=(10, 4))
    plt.plot(avg_actions, color='steelblue')
    plt.xlabel('Step')
    plt.ylabel('Average Action')
    plt.title('PPO Average Aggression Level Over Episode')
    plt.yticks([0,1,2,3,4], ['Nothing','Passive Sm','Passive Lg','Aggressive','Market'])
    plt.tight_layout()
    plt.savefig(f'{SAVE_PATH}/action_over_time.png', dpi=150)
    plt.show()

plot_action_over_time()