from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]

RAW_EVENTS_PATH = REPO_ROOT / "data/raw/events/FOMC_signals_raw_2022_2024.csv"
RAW_CLEANED_TRADES_DIR = REPO_ROOT / "data/raw/cleaned trades"

PROCESSED_DIR = REPO_ROOT / "data/processed"
PLOTS_DIR = REPO_ROOT / "results/plots/cpi_trade_research"

FEATURES_OUTPUT_PATH = PROCESSED_DIR / "cpi_trade_features.csv"
SIGNALS_OUTPUT_PATH = PROCESSED_DIR / "cpi_trade_signal_results.csv"
VALIDATION_OUTPUT_PATH = PROCESSED_DIR / "cpi_trade_validation_summary.csv"

EASTERN_TZ = "America/New_York"
RELEASE_HOUR_ET = 14
RELEASE_MINUTE_ET = 0
SURPRISE_THRESHOLD = 0.1

PRE_WINDOW_MINUTES = 120
POST_WINDOW_MINUTES = 120
IMPACT_WINDOW_MINUTES = 5

OFI_ROLLING_MINUTES = 5
ARRIVAL_RATE_ROLLING_MINUTES = 1
FINAL_ACCELERATION_LOOKBACK_MINUTES = 10

OFI_IMPACT_WINDOWS_SECONDS = [30, 60, 120, 300]
TARGET_MOVE_PCTS = [0.005, 0.01, 0.015]
RETURN_HORIZONS_MINUTES = [5, 15, 30, 60, 120]
SIGNAL_HORIZONS_MINUTES = [30, 60, 120]

SIGNAL_A_OFI_THRESHOLD = 0.10

SIGNAL_C_RATIO_TREND_THRESHOLD = 0.8
SIGNAL_C_RATIO_REVERSAL_THRESHOLD = 0.2

WALK_FORWARD_INITIAL_TRAIN = 25
LOOCV_MIN_TRAIN_SIZE = 10
PERMUTATION_ITERATIONS = 1_000
RANDOM_SEED = 42

