#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$ROOT_DIR/scripts/component_lib.sh"

ensure_venv frontend/requirements.txt

HOST="${FRONTEND_DSQL_HOST:-${DSQL_HOST:-4btv7qq43k4ztw3tjubmbyf3su.dsql.us-east-2.on.aws}}"
REGION="${FRONTEND_AWS_REGION:-${AWS_REGION:-us-east-2}}"
FRONTEND_HOST="${FRONTEND_HOST:-0.0.0.0}"
FRONTEND_PORT="${FRONTEND_PORT:-8080}"
FRONTEND_LISTENER_HOST="${FRONTEND_LISTENER_HOST:-127.0.0.1}"
FRONTEND_LISTENER_PORT="${FRONTEND_LISTENER_PORT:-9001}"
FRONTEND_LISTENER_AUTH_TOKEN="${FRONTEND_LISTENER_AUTH_TOKEN:-${CLIENT_LISTENER_AUTH_TOKEN:-dev-shared-token}}"
FRONTEND_BOOTSTRAP_ADMIN_USERNAME="${FRONTEND_BOOTSTRAP_ADMIN_USERNAME:-admin}"
FRONTEND_BOOTSTRAP_ADMIN_PASSWORD="${FRONTEND_BOOTSTRAP_ADMIN_PASSWORD:-MarketAdmin!2026Forever}"
FRONTEND_SESSION_TTL_SECONDS="${FRONTEND_SESSION_TTL_SECONDS:-86400}"
FRONTEND_SESSION_SECURE_COOKIE="${FRONTEND_SESSION_SECURE_COOKIE:-false}"

refresh_dsql_dsn FRONTEND_DB_DSN "$HOST" "$REGION"

exec env \
  FRONTEND_HOST="$FRONTEND_HOST" \
  FRONTEND_PORT="$FRONTEND_PORT" \
  FRONTEND_LISTENER_HOST="$FRONTEND_LISTENER_HOST" \
  FRONTEND_LISTENER_PORT="$FRONTEND_LISTENER_PORT" \
  FRONTEND_LISTENER_AUTH_TOKEN="$FRONTEND_LISTENER_AUTH_TOKEN" \
  FRONTEND_BOOTSTRAP_ADMIN_USERNAME="$FRONTEND_BOOTSTRAP_ADMIN_USERNAME" \
  FRONTEND_BOOTSTRAP_ADMIN_PASSWORD="$FRONTEND_BOOTSTRAP_ADMIN_PASSWORD" \
  FRONTEND_SESSION_TTL_SECONDS="$FRONTEND_SESSION_TTL_SECONDS" \
  FRONTEND_SESSION_SECURE_COOKIE="$FRONTEND_SESSION_SECURE_COOKIE" \
  FRONTEND_DB_DSN="$FRONTEND_DB_DSN" \
  DB_DSN="$FRONTEND_DB_DSN" \
  "$PYTHON_BIN" "$SCRIPT_DIR/server.py"
