#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$ROOT_DIR/scripts/component_lib.sh"

ensure_venv executor/requirements.txt

HOST="${EXECUTOR_DSQL_HOST:-${DSQL_HOST:-4btv7qq43k4ztw3tjubmbyf3su.dsql.us-east-2.on.aws}}"
REGION="${EXECUTOR_AWS_REGION:-${AWS_REGION:-us-east-2}}"
EXECUTOR_INSTANCE_ID="${EXECUTOR_INSTANCE_ID:-executor-a}"
EXECUTOR_POLL_INTERVAL_MS="${EXECUTOR_POLL_INTERVAL_MS:-1000}"
EXECUTOR_MARKET_SCAN_LIMIT="${EXECUTOR_MARKET_SCAN_LIMIT:-50}"
EXECUTOR_LEASE_SECONDS="${EXECUTOR_LEASE_SECONDS:-10}"

refresh_dsql_dsn EXECUTOR_DB_DSN "$HOST" "$REGION"

exec env \
  EXECUTOR_DB_DSN="$EXECUTOR_DB_DSN" \
  EXECUTOR_INSTANCE_ID="$EXECUTOR_INSTANCE_ID" \
  EXECUTOR_POLL_INTERVAL_MS="$EXECUTOR_POLL_INTERVAL_MS" \
  EXECUTOR_MARKET_SCAN_LIMIT="$EXECUTOR_MARKET_SCAN_LIMIT" \
  EXECUTOR_LEASE_SECONDS="$EXECUTOR_LEASE_SECONDS" \
  "$PYTHON_BIN" "$SCRIPT_DIR/executor.py"
